site_name: RegelRecht
site_description: Van wet naar digitale werking
site_url: https://regelrecht.nl
repo_url: https://github.com/MinBZK/poc-machine-law
repo_name: MinBZK/poc-machine-law

nav:
  - Home: index.md
  - Tools: tools.md
  - Blog: blog/index.md
  - Gerelateerde Projecten: gerelateerde-projecten.md
  - Team: team.md
  - FAQ: faq.md

theme:
  name: material
  language: nl
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Schakel naar donkere modus
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Schakel naar lichte modus
  font:
    text: RO Sans
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/extra.js

plugins:
  - search:
      lang: nl

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MinBZK/poc-machine-law
    - icon: fontawesome/solid/envelope
      link: mailto:regelrecht@minbzk.nl
  analytics:
    provider: google
    property: G-XXXXXXXXXX

copyright: "Copyright &copy; 2025 Ministerie van Binnenlandse Zaken en Koninkrijksrelaties"