/**
 * Record that every current English string was translated from the current Dutch.
 *
 * Run this after a translation pass. It rewrites `src/i18n/en.sources.js` with
 * one hash per key, and that file is what `i18n.test.js` compares against to
 * tell a fresh translation from one that was left behind when its Dutch
 * original changed.
 *
 * Deliberately dumb: it blesses whatever is there. That is safe only because
 * running it is an explicit act at the end of translating — never something a
 * build does on its own, which would make the staleness check bless away the
 * very thing it exists to catch.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hash } from '../src/i18n/hash.js';
import nl from '../src/i18n/nl.js';

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, '..', 'src', 'i18n', 'en.sources.js');

const header = `/**
 * Per key, the fingerprint of the Dutch string its English translation was made
 * from. Generated by \`node scripts/i18n-bless.mjs\` — never edited by hand.
 *
 * A mismatch means the Dutch moved and the English did not. \`i18n.test.js\`
 * fails on it and names the keys, so retranslate those and run the script again.
 */
export default {
`;

const body = Object.keys(nl)
  .sort()
  .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(hash(nl[key]))},`)
  .join('\n');

const next = `${header}${body}\n};\n`;

let previous = null;
try {
  previous = readFileSync(target, 'utf8');
} catch {
  // First run: the file does not exist yet.
}

if (previous === next) {
  console.log(`i18n: ${Object.keys(nl).length} bronhashes ongewijzigd.`);
} else {
  writeFileSync(target, next);
  console.log(`i18n: ${Object.keys(nl).length} bronhashes bijgewerkt in src/i18n/en.sources.js.`);
}
