//! Precomputed implements-index: the committed artefact that replaces the
//! O(corpus) `read_all_implements` scan.
//!
//! The index is a JSON file at the **root of the corpus repository**
//! ([`IMPLEMENTS_INDEX_FILENAME`]), generated by the `implements-indexer`
//! binary (run by CI in the corpus repo) and consumed by
//! [`RepoBackend::read_all_implements`] implementations. It maps every
//! YAML file under a scanned subtree to the `$id`s of the higher laws that
//! file declares it `implements` (RFC-003 IoC resolution).
//!
//! ## Contract
//!
//! - **One entry per YAML file, including files that implement nothing.**
//!   The consumer (`traject_corpus`'s implements-index build) uses the map
//!   as a *negative cache*: a path missing from the result falls through to
//!   a per-law body fetch + parse. Omitting the ~22k empty entries would
//!   re-fetch nearly the whole corpus on every snapshot TTL.
//! - **`.yml` counts alongside `.yaml`**, matching the tarball scan in
//!   [`crate::github`].
//! - **Unparseable laws are omitted, never indexed as empty.**
//!   `collect_law_implements` degrades a parse failure to "implements
//!   nothing"; committing that to an index would make the failure
//!   permanent and invisible. The scan therefore uses the fallible parse
//!   and reports failures separately, and the generator leaves those paths
//!   out of the index — a missing key means "fetch and parse this law",
//!   which is exactly the behaviour without an index. See
//!   [`generator`] for how a *systematic* parse failure is caught.
//! - **Branch/checkout freshness is verifiable.** The index records the
//!   git tree sha of the scanned subtree (`tree_sha`). A consumer compares
//!   it against the same subtree in its own checkout (`git rev-parse
//!   HEAD:<root>`, or the Trees API for API-based backends): equal means
//!   the index describes exactly this checkout's content, regardless of
//!   which branch that is. This is what catches a corpus branch (e.g. a
//!   `pr<N>` preview branch) that received commits after the index was
//!   last regenerated.
//!
//! The index deliberately lives *outside* the source sandbox: sources are
//! rooted at a subtree (e.g. `regulation/nl`, see `corpus-registry.yaml`)
//! and backend path resolution prefixes every relative path with that
//! root, so backends read the root file directly off the repo/checkout
//! root, not through their sandboxed path resolution.
//!
//! [`RepoBackend::read_all_implements`]: crate::backend::RepoBackend::read_all_implements

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::{CorpusError, Result};

pub mod generator;

/// Filename of the index at the corpus repository root.
pub const IMPLEMENTS_INDEX_FILENAME: &str = "implements-index.json";

/// Current format version. Bump on breaking format changes; consumers
/// reject other versions (and fall back to scanning) rather than
/// misinterpreting the file.
pub const IMPLEMENTS_INDEX_VERSION: u32 = 1;

/// The committed index artefact.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ImplementsIndex {
    /// Format version — see [`IMPLEMENTS_INDEX_VERSION`].
    pub version: u32,
    /// Repo-relative subtree the scan covered (e.g. `"regulation"`).
    /// Recorded so the consumer verifies freshness against the same
    /// subtree the generator hashed, and so the index file itself (at the
    /// repo root, outside this subtree) never invalidates its own hash.
    pub root: String,
    /// Git tree sha of `root` at generation time (`git rev-parse
    /// HEAD:<root>` on a clean checkout).
    pub tree_sha: String,
    /// Repo-relative path → `$id`s of the higher laws the file declares it
    /// `implements`. One entry for **every** `.yaml`/`.yml` file under
    /// `root`, empty list included — consumers rely on missing-key ≠
    /// implements-nothing. `BTreeMap` keeps serialization deterministic
    /// (stable diffs in the corpus repo).
    pub files: BTreeMap<String, Vec<String>>,
}

impl ImplementsIndex {
    /// Serialize to the canonical on-disk JSON form (pretty-printed:
    /// one file entry per line, so corpus-repo diffs stay line-based).
    pub fn to_json(&self) -> String {
        // Serialization of this plain struct cannot fail.
        let mut out = serde_json::to_string_pretty(self).unwrap_or_default();
        out.push('\n');
        out
    }

    /// Parse the on-disk JSON form. Rejects unknown format versions so a
    /// future format is never silently misread as an empty/partial index.
    pub fn parse(json: &str) -> Result<Self> {
        let index: Self = serde_json::from_str(json)
            .map_err(|e| CorpusError::Config(format!("implements index is not valid JSON: {e}")))?;
        if index.version != IMPLEMENTS_INDEX_VERSION {
            return Err(CorpusError::Config(format!(
                "implements index has unsupported version {} (expected {})",
                index.version, IMPLEMENTS_INDEX_VERSION
            )));
        }
        // An index over the repo root contains its own file, so the tree
        // sha it records is invalidated by writing it and can never
        // verify. Such a file can only be a mistake; refuse it here so a
        // consumer falls back instead of reasoning about it. The generator
        // refuses to produce one for the same reason.
        if normalise_root(&index.root).is_empty() {
            return Err(CorpusError::Config(
                "implements index is rooted at the repo root, where its own file \
                 invalidates the tree sha it records"
                    .to_string(),
            ));
        }
        Ok(index)
    }

    /// Whether this index actually describes a source rooted at
    /// `sub_path`. The scan only covered [`Self::root`], so a source rooted
    /// elsewhere (a differently-rooted registry entry, or an index
    /// generated with a narrower `--root`) is simply not described here.
    ///
    /// Without this check [`Self::to_source_relative`] would return an
    /// empty list for such a source, which the consumer cannot distinguish
    /// from "this corpus contains no laws" — it would read as a complete,
    /// authoritative, empty answer.
    pub fn covers(&self, sub_path: Option<&str>) -> bool {
        let root = self.root.trim_matches('/');
        match sub_path {
            Some(sub) if !sub.trim_matches('/').is_empty() => {
                let sub = sub.trim_matches('/');
                root.is_empty() || sub == root || sub.starts_with(&format!("{root}/"))
            }
            // A source at the repo root is covered only by a repo-root
            // scan; a `regulation`-rooted index would silently omit
            // everything outside it.
            _ => root.is_empty(),
        }
    }

    /// Project the repo-relative entries onto a source rooted at
    /// `sub_path`: strips the `sub_path` prefix and **drops** entries
    /// outside it (mirrors `GitHubApiBackend::to_source_relative`). With
    /// no `sub_path` the entries pass through unchanged.
    ///
    /// The root is normalised exactly as [`Self::covers`] normalises it
    /// (both ends trimmed of `/`). They have to agree: a `sub_path` that
    /// passes `covers` but strips no prefix would project to an empty list,
    /// and the caller reads an empty list as an authoritative "this corpus
    /// holds no laws".
    pub fn to_source_relative(&self, sub_path: Option<&str>) -> Vec<(String, Vec<String>)> {
        match sub_path.map(|s| s.trim_matches('/')) {
            Some(sub) if !sub.is_empty() => {
                let prefix = format!("{sub}/");
                self.files
                    .iter()
                    .filter_map(|(path, implements)| {
                        path.strip_prefix(&prefix)
                            .map(|rel| (rel.to_string(), implements.clone()))
                    })
                    .collect()
            }
            _ => self
                .files
                .iter()
                .map(|(path, implements)| (path.clone(), implements.clone()))
                .collect(),
        }
    }
}

/// What kind of loss a [`ScanFailure`] represents. The two are gated
/// differently by the generator: a per-file failure names exactly one path
/// that stays out of the index, a walk failure names a directory whose
/// contents were never enumerated at all.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScanFailureKind {
    /// A known `.yaml`/`.yml` file that could not be read or parsed. The
    /// loss is exactly one path, and a path missing from the index means
    /// "fetch and parse this law" — the behaviour without an index.
    File,
    /// A directory the walk could not enter (permissions, a vanished
    /// path). How many laws are behind it is unknown, so the ratio net
    /// over per-file failures says nothing about the size of this hole.
    Walk,
}

/// One thing the scan could not take in. Recorded instead of silently
/// indexing a file as "implements nothing" or dropping a subtree.
#[derive(Debug)]
pub struct ScanFailure {
    /// Repo-relative path of the failing file or directory.
    pub path: String,
    /// The error, for the generator's failure report.
    pub error: String,
    /// Whether one file was lost or a whole directory went unseen.
    pub kind: ScanFailureKind,
}

/// Result of [`scan_tree`]: the per-file entries plus every file that
/// failed to parse. The caller decides what failures mean — the generator
/// refuses to emit an index when any are present.
#[derive(Debug)]
pub struct ScanOutcome {
    /// Repo-relative path → implements list, for every parseable
    /// `.yaml`/`.yml` file under the scanned root.
    pub files: BTreeMap<String, Vec<String>>,
    pub failures: Vec<ScanFailure>,
}

/// Walk `<repo_root>/<scan_root>` and collect the implements list of every
/// `.yaml`/`.yml` file. Paths in the result are repo-relative (i.e. they
/// start with `<scan_root>/`), matching what the committed index stores.
///
/// Synchronous and CPU/IO-bound — the generator is a batch binary; async
/// callers should wrap in `spawn_blocking`. Symlinks are not followed,
/// consistent with the backend tree walks and the tarball extraction
/// (which only reads regular entries).
pub fn scan_tree(repo_root: &Path, scan_root: &str) -> Result<ScanOutcome> {
    let scan_root = normalised_scan_root(scan_root)?;
    let abs_root = repo_root.join(&scan_root);
    if !abs_root.is_dir() {
        return Err(CorpusError::Config(format!(
            "scan root does not exist or is not a directory: {}",
            abs_root.display()
        )));
    }

    let mut files = BTreeMap::new();
    let mut failures = Vec::new();

    for entry in walkdir::WalkDir::new(&abs_root) {
        let entry = match entry {
            Ok(entry) => entry,
            Err(e) => {
                // A directory the walk cannot enter takes an unknown
                // number of laws with it. Dropping it here would produce
                // an index that looks complete, which is the one thing
                // this scan must never hand its consumer.
                let path = e
                    .path()
                    .and_then(|p| repo_relative(repo_root, p))
                    .unwrap_or_else(|| scan_root.clone());
                failures.push(ScanFailure {
                    path,
                    error: format!("walk failed: {e}"),
                    kind: ScanFailureKind::Walk,
                });
                continue;
            }
        };
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        let is_yaml = path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|ext| ext == "yaml" || ext == "yml");
        if !is_yaml {
            continue;
        }
        let Some(rel) = repo_relative(repo_root, path) else {
            continue;
        };

        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(e) => {
                failures.push(ScanFailure {
                    path: rel,
                    error: format!("read failed: {e}"),
                    kind: ScanFailureKind::File,
                });
                continue;
            }
        };
        match crate::source_map::try_collect_law_implements(&content) {
            Ok(implements) => {
                files.insert(rel, implements);
            }
            Err(e) => failures.push(ScanFailure {
                path: rel,
                error: e.to_string(),
                kind: ScanFailureKind::File,
            }),
        }
    }

    Ok(ScanOutcome { files, failures })
}

/// The scan root in the one spelling everything downstream assumes:
/// normalised, and inside the repository.
///
/// Normalising before the root is joined onto the checkout is what keeps
/// the scan there at all — `Path::join` with an absolute path discards
/// what it was joined to, so an unnormalised `/regulation` would walk an
/// absolute filesystem path. A `..` cannot be normalised away without
/// changing which directory is meant, so it is refused instead.
pub fn normalised_scan_root(root: &str) -> Result<String> {
    let root = normalise_root(root);
    if root.split('/').any(|segment| segment == "..") {
        return Err(CorpusError::Config(format!(
            "scan root must stay inside the repository, not climb out of it: '{root}'"
        )));
    }
    Ok(root)
}

/// Collapse a scan root to the form the consumer compares and strips with:
/// no leading or trailing slash, no empty or `.` segment. Shared with the
/// generator, which records the result in the index — the two must agree,
/// or a root the index accepts strips no prefix and projects to an empty
/// map that reads as "this corpus holds no laws".
pub fn normalise_root(root: &str) -> String {
    root.split('/')
        .filter(|segment| !segment.is_empty() && *segment != ".")
        .collect::<Vec<_>>()
        .join("/")
}

/// `path` relative to `repo_root`, with forward slashes, matching
/// git/GitHub paths. `None` when `path` lies outside `repo_root`.
fn repo_relative(repo_root: &Path, path: &Path) -> Option<String> {
    let rel = path.strip_prefix(repo_root).ok()?;
    Some(
        rel.components()
            .filter_map(|c| match c {
                std::path::Component::Normal(s) => s.to_str(),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("/"),
    )
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn write(root: &Path, rel: &str, content: &str) {
        let path = root.join(rel);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    const IMPLEMENTING_LAW: &str = "\
$id: regeling_x
articles:
  - number: '1'
    machine_readable:
      implements:
        - law: wet_hoger
          open_term: iets
";

    #[test]
    fn scan_indexes_every_yaml_including_empty_and_yml() {
        let dir = TempDir::new().unwrap();
        write(
            dir.path(),
            "regulation/nl/wet/wet_hoger/2025-01-01.yaml",
            "$id: wet_hoger\narticles: []\n",
        );
        write(
            dir.path(),
            "regulation/nl/regeling/regeling_x/2025-01-01.yaml",
            IMPLEMENTING_LAW,
        );
        // `.yml` must be scanned too — a `.yaml`-only generator loses
        // these laws silently (they'd fall through the negative cache).
        write(
            dir.path(),
            "regulation/nl/wet/wet_kort/2025-01-01.yml",
            "$id: wet_kort\narticles: []\n",
        );
        // Non-YAML files are ignored.
        write(dir.path(), "regulation/nl/wet/wet_hoger/notes.md", "tekst");
        // Files outside the scan root are ignored.
        write(
            dir.path(),
            "elders/other.yaml",
            "$id: other\narticles: []\n",
        );

        let outcome = scan_tree(dir.path(), "regulation").unwrap();
        assert!(outcome.failures.is_empty());

        // An entry for EVERY yaml/yml file — empty implements included.
        let paths: Vec<&str> = outcome.files.keys().map(String::as_str).collect();
        assert_eq!(
            paths,
            vec![
                "regulation/nl/regeling/regeling_x/2025-01-01.yaml",
                "regulation/nl/wet/wet_hoger/2025-01-01.yaml",
                "regulation/nl/wet/wet_kort/2025-01-01.yml",
            ]
        );
        assert_eq!(
            outcome.files["regulation/nl/regeling/regeling_x/2025-01-01.yaml"],
            vec!["wet_hoger".to_string()]
        );
        assert!(outcome.files["regulation/nl/wet/wet_hoger/2025-01-01.yaml"].is_empty());
        assert!(outcome.files["regulation/nl/wet/wet_kort/2025-01-01.yml"].is_empty());
    }

    #[test]
    fn scan_reports_unparseable_files_instead_of_indexing_them_empty() {
        let dir = TempDir::new().unwrap();
        write(
            dir.path(),
            "regulation/nl/wet/wet_ok/2025-01-01.yaml",
            "$id: wet_ok\narticles: []\n",
        );
        write(
            dir.path(),
            "regulation/nl/wet/wet_kapot/2025-01-01.yaml",
            "name: \"unterminated\nfoo: bar\n",
        );

        let outcome = scan_tree(dir.path(), "regulation").unwrap();
        assert_eq!(outcome.failures.len(), 1);
        assert_eq!(
            outcome.failures[0].path,
            "regulation/nl/wet/wet_kapot/2025-01-01.yaml"
        );
        // The broken file is NOT in the map — it must never be recorded
        // as "implements nothing".
        assert!(!outcome
            .files
            .contains_key("regulation/nl/wet/wet_kapot/2025-01-01.yaml"));
        assert!(outcome
            .files
            .contains_key("regulation/nl/wet/wet_ok/2025-01-01.yaml"));
    }

    /// Restores the mode of a directory the test made unreadable. A
    /// `Drop` guard rather than a call after the body: a failing assertion
    /// inside the body would otherwise leave a 0o000 directory that
    /// `TempDir` cannot clean up.
    #[cfg(unix)]
    pub(super) struct Unreadable<'a> {
        path: &'a Path,
        original: fs::Permissions,
    }

    #[cfg(unix)]
    impl Drop for Unreadable<'_> {
        fn drop(&mut self) {
            let _ = fs::set_permissions(self.path, self.original.clone());
        }
    }

    /// Make `path` unreadable until the returned guard is dropped.
    #[cfg(unix)]
    pub(super) fn make_unreadable(path: &Path) -> Unreadable<'_> {
        use std::os::unix::fs::PermissionsExt;
        let original = fs::metadata(path).unwrap().permissions();
        fs::set_permissions(path, fs::Permissions::from_mode(0o000)).unwrap();
        Unreadable { path, original }
    }

    /// Whether mode bits actually keep *this* process out of a directory.
    /// They don't for uid 0, and some CI images run tests as root — there
    /// the unreadable-directory tests would assert a failure that cannot
    /// occur, so they skip instead of failing for the wrong reason.
    #[cfg(unix)]
    pub(super) fn directory_permissions_bite() -> bool {
        let scratch = TempDir::new().unwrap();
        let probe = scratch.path().join("probe");
        fs::create_dir_all(&probe).unwrap();
        let _locked = make_unreadable(&probe);
        fs::read_dir(&probe).is_err()
    }

    #[cfg(unix)]
    #[test]
    fn an_unreadable_directory_is_a_scan_failure_not_a_silent_hole() {
        let dir = TempDir::new().unwrap();
        if !directory_permissions_bite() {
            eprintln!("skipped: this process reads directories regardless of mode bits");
            return;
        }
        write(
            dir.path(),
            "regulation/nl/wet/wet_ok/2025-01-01.yaml",
            "$id: wet_ok\narticles: []\n",
        );
        write(
            dir.path(),
            "regulation/nl/geheim/wet_weg/2025-01-01.yaml",
            "$id: wet_weg\narticles: []\n",
        );

        let locked = dir.path().join("regulation/nl/geheim");
        let _guard = make_unreadable(&locked);
        let outcome = scan_tree(dir.path(), "regulation").unwrap();

        // The laws behind the locked directory are gone from the index
        // either way; what must not happen is that they go quietly.
        assert!(!outcome.files.keys().any(|k| k.contains("wet_weg")));
        let walk: Vec<&ScanFailure> = outcome
            .failures
            .iter()
            .filter(|f| f.kind == ScanFailureKind::Walk)
            .collect();
        assert_eq!(
            walk.len(),
            1,
            "an unreadable directory must surface as a failure, got {:?}",
            outcome.failures
        );
        assert!(
            walk[0].path.contains("geheim"),
            "the failure must name the directory: {:?}",
            walk[0]
        );
        // The readable half is still indexed.
        assert!(outcome
            .files
            .contains_key("regulation/nl/wet/wet_ok/2025-01-01.yaml"));
    }

    #[test]
    fn scan_root_is_normalised_before_it_is_joined() {
        let dir = TempDir::new().unwrap();
        write(
            dir.path(),
            "regulation/nl/wet/wet_ok/2025-01-01.yaml",
            "$id: wet_ok\narticles: []\n",
        );

        // A leading slash is decorative for `covers`/`to_source_relative`,
        // so it must be here too — `join` with an absolute path would drop
        // `repo_root` and scan outside the checkout entirely.
        for root in ["/regulation", "regulation/", "./regulation", "regulation//"] {
            let outcome = scan_tree(dir.path(), root).unwrap();
            assert_eq!(
                outcome.files.len(),
                1,
                "root {root} must resolve inside the checkout"
            );
        }

        assert!(scan_tree(dir.path(), "../etc").is_err());
    }

    #[test]
    fn normalise_root_drops_decoration_and_current_dir() {
        assert_eq!(normalise_root("regulation"), "regulation");
        assert_eq!(normalise_root("/regulation/nl/"), "regulation/nl");
        assert_eq!(normalise_root("regulation//nl"), "regulation/nl");
        // `.` names the repo root exactly as `/` does; both must collapse
        // to the empty root the generator refuses.
        assert_eq!(normalise_root("."), "");
        assert_eq!(normalise_root("./"), "");
        assert_eq!(normalise_root("./regulation"), "regulation");
    }

    #[test]
    fn scan_missing_root_is_an_error() {
        let dir = TempDir::new().unwrap();
        assert!(scan_tree(dir.path(), "regulation").is_err());
    }

    #[test]
    fn json_roundtrip_preserves_index() {
        let mut files = BTreeMap::new();
        files.insert(
            "regulation/nl/wet/a/2025-01-01.yaml".to_string(),
            Vec::new(),
        );
        files.insert(
            "regulation/nl/regeling/b/2025-01-01.yaml".to_string(),
            vec!["a".to_string()],
        );
        let index = ImplementsIndex {
            version: IMPLEMENTS_INDEX_VERSION,
            root: "regulation".to_string(),
            tree_sha: "abc123".to_string(),
            files,
        };
        let parsed = ImplementsIndex::parse(&index.to_json()).unwrap();
        assert_eq!(parsed, index);
    }

    #[test]
    fn parse_rejects_unknown_version_and_garbage() {
        let json = r#"{"version": 999, "root": "regulation", "tree_sha": "x", "files": {}}"#;
        let err = ImplementsIndex::parse(json).unwrap_err().to_string();
        assert!(err.contains("version"), "unexpected error: {err}");

        assert!(ImplementsIndex::parse("not json").is_err());

        // A repo-root index cannot verify against anything — see `parse`.
        let rooted_at_repo = r#"{"version": 1, "root": "", "tree_sha": "x", "files": {}}"#;
        let err = ImplementsIndex::parse(rooted_at_repo)
            .unwrap_err()
            .to_string();
        assert!(err.contains("repo root"), "unexpected error: {err}");
    }

    #[test]
    fn covers_only_sources_inside_the_scanned_root() {
        let index = ImplementsIndex {
            version: IMPLEMENTS_INDEX_VERSION,
            root: "regulation".to_string(),
            tree_sha: "abc".to_string(),
            files: BTreeMap::new(),
        };

        assert!(index.covers(Some("regulation")));
        assert!(index.covers(Some("regulation/nl")));
        assert!(index.covers(Some("regulation/nl/")));

        // A sibling that merely shares a prefix is NOT inside the root.
        assert!(!index.covers(Some("regulations")));
        // A source rooted above the scan: the index says nothing about
        // everything outside `regulation`, so it must not be served.
        assert!(!index.covers(None));
        assert!(!index.covers(Some("")));

        // A repo-root scan covers every source.
        let whole = ImplementsIndex {
            root: String::new(),
            ..index
        };
        assert!(whole.covers(None));
        assert!(whole.covers(Some("regulation/nl")));
    }

    #[test]
    fn to_source_relative_strips_sub_path_and_drops_outside_entries() {
        let mut files = BTreeMap::new();
        files.insert(
            "regulation/nl/wet/a/2025-01-01.yaml".to_string(),
            vec!["hoger".to_string()],
        );
        // Outside the source root (`regulation/nl`): dropped, exactly like
        // `GitHubApiBackend::to_source_relative` drops repo-root config.
        files.insert(
            "regulation/be/wet/b/2025-01-01.yaml".to_string(),
            Vec::new(),
        );
        let index = ImplementsIndex {
            version: IMPLEMENTS_INDEX_VERSION,
            root: "regulation".to_string(),
            tree_sha: "abc".to_string(),
            files,
        };

        let mapped = index.to_source_relative(Some("regulation/nl"));
        assert_eq!(
            mapped,
            vec![(
                "wet/a/2025-01-01.yaml".to_string(),
                vec!["hoger".to_string()]
            )]
        );

        // A slash on either end is tolerated. It has to be: `covers`
        // trims both ends, so a root it accepts must also project — an
        // accepted root that strips no prefix yields an empty list, which
        // the caller reads as "this corpus holds no laws".
        for sub in ["regulation/nl/", "/regulation/nl", "/regulation/nl/"] {
            assert_eq!(
                index.to_source_relative(Some(sub)).len(),
                1,
                "root {sub} passes covers ({}) but projects to nothing",
                index.covers(Some(sub))
            );
            assert!(index.covers(Some(sub)));
        }

        // No sub_path: passthrough.
        let all = index.to_source_relative(None);
        assert_eq!(all.len(), 2);
    }
}
