#!/usr/bin/env node
// Load a case manifest into regelrecht-mvp.
//
// Reads cases/<slug>/scope.yaml and:
// - regenerates .scope/ with symlinks to each in-scope corpus directory
// - writes corpus-registry.local.yaml that overrides the default registry
//   to use only .scope/ (and disables the minbzk-central GitHub source)
//
// Servers (editor-api, Vite) are NOT restarted — do that yourself.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from 'fs';
import { dirname, join, relative, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const CORPUS_ROOT = resolve(REPO_ROOT, 'corpus', 'regulation', 'nl');
const CASES_ROOT = resolve(REPO_ROOT, 'cases');
const SCOPE_DIR = resolve(REPO_ROOT, '.scope');
const REGISTRY_LOCAL = resolve(REPO_ROOT, 'corpus-registry.local.yaml');

// Reuse js-yaml from the frontend's node_modules.
let yaml;
try {
  yaml = (await import(join(REPO_ROOT, 'frontend', 'node_modules', 'js-yaml', 'dist', 'js-yaml.mjs'))).default;
} catch (e) {
  console.error('error: could not load js-yaml from frontend/node_modules.');
  console.error('Run `cd frontend && npm install` first, or install js-yaml globally.');
  process.exit(1);
}

function findLawDir(lawId, layer) {
  // An in-corpus directory whose $id matches lawId. Organisational nesting
  // (e.g. waterschaps_verordening/hhnk/<dir>) strips the `_<org>` suffix
  // from the dir name, so we look for both lawId and id-minus-suffix.
  const candidates = [lawId];
  const parts = lawId.split('_');
  for (let i = 1; i < parts.length; i++) {
    candidates.push(parts.slice(0, -i).join('_'));
  }

  const roots = layer ? [join(CORPUS_ROOT, layer)] : [CORPUS_ROOT];
  for (const root of roots) {
    if (!existsSync(root)) continue;
    // Depth-first up to 3 levels (layer/org/dir is typical max).
    const walk = (dir, depth) => {
      if (depth > 3) return null;
      for (const name of readdirSync(dir)) {
        const full = join(dir, name);
        if (!statSync(full).isDirectory()) continue;
        if (candidates.includes(name) && hasLawIdMatching(full, lawId)) return full;
        const deeper = walk(full, depth + 1);
        if (deeper) return deeper;
      }
      return null;
    };
    const hit = walk(root, 0);
    if (hit) return hit;
  }
  return null;
}

function hasLawIdMatching(dir, lawId) {
  // Verify by reading the first YAML in the dir and checking $id.
  for (const name of readdirSync(dir)) {
    if (!name.endsWith('.yaml')) continue;
    const content = readFileSync(join(dir, name), 'utf-8');
    const idMatch = content.match(/^\$id:\s*['"]?([a-z_0-9]+)['"]?/m);
    if (idMatch && idMatch[1] === lawId) return true;
    // If we found a YAML but the id doesn't match, do not accept this dir.
    return false;
  }
  return false;
}

function loadScope(slug) {
  const file = join(CASES_ROOT, slug, 'scope.yaml');
  if (!existsSync(file)) {
    console.error(`error: case '${slug}' not found at ${file}`);
    process.exit(1);
  }
  return yaml.load(readFileSync(file, 'utf-8'));
}

function clearScope() {
  if (existsSync(SCOPE_DIR)) rmSync(SCOPE_DIR, { recursive: true, force: true });
  if (existsSync(REGISTRY_LOCAL)) rmSync(REGISTRY_LOCAL, { force: true });
}

function writeRegistry(caseName) {
  const content = `---
# Auto-generated by script/case-load.js
# Do not edit by hand — re-run \`just case-load <slug>\` to regenerate.
schema_version: '1.0'
sources:
  - id: local
    name: ${JSON.stringify(caseName)}
    type: local
    local:
      path: .scope
    scopes: []
    priority: 1

  - id: minbzk-central
    name: "minbzk-central (disabled for scope)"
    type: local
    local:
      path: /nonexistent-disabled
    scopes: []
    priority: 99
`;
  writeFileSync(REGISTRY_LOCAL, content);
}

function listCases() {
  if (!existsSync(CASES_ROOT)) {
    console.log('(no cases/ directory)');
    return;
  }
  let found = false;
  for (const name of readdirSync(CASES_ROOT).sort()) {
    const full = join(CASES_ROOT, name);
    const scopeFile = join(full, 'scope.yaml');
    if (statSync(full).isDirectory() && existsSync(scopeFile)) {
      const scope = yaml.load(readFileSync(scopeFile, 'utf-8'));
      console.log(`  ${name.padEnd(40)} ${scope.name || '?'}`);
      found = true;
    }
  }
  if (!found) console.log('(no cases defined)');
}

function loadCase(slug) {
  const scope = loadScope(slug);
  console.log(`Loading case '${slug}': ${scope.name}`);

  clearScope();
  mkdirSync(SCOPE_DIR, { recursive: true });

  const loaded = [];
  const missing = [];

  for (const entry of scope.laws || []) {
    const lawId = entry.id;
    const src = findLawDir(lawId, entry.layer);
    if (!src) {
      missing.push(lawId);
      continue;
    }
    const rel = relative(CORPUS_ROOT, src);
    const link = join(SCOPE_DIR, rel);
    mkdirSync(dirname(link), { recursive: true });
    symlinkSync(src, link);
    loaded.push([lawId, rel]);
  }

  writeRegistry(scope.name || slug);

  console.log(`  symlinks: ${loaded.length} created in .scope/`);
  for (const [lawId, rel] of loaded) {
    console.log(`    ${lawId.padEnd(55)} -> ${rel}`);
  }
  if (missing.length) {
    console.log(`  missing: ${missing.length} law(s) not found in corpus:`);
    for (const lawId of missing) console.log(`    ${lawId}`);
  }
  console.log(`  registry: ${REGISTRY_LOCAL.split('/').pop()} written`);
  console.log();
  console.log('Restart editor-api and Vite to pick up the new scope.');
}

const [, , cmd, arg] = process.argv;
switch (cmd) {
  case 'load':
    if (!arg) { console.error('usage: case-load.js load <slug>'); process.exit(1); }
    loadCase(arg);
    break;
  case 'list':
    listCases();
    break;
  case 'clear':
    clearScope();
    console.log('cleared .scope/ and corpus-registry.local.yaml');
    break;
  default:
    console.error('usage: case-load.js {load <slug> | list | clear}');
    process.exit(1);
}
