#!/usr/bin/env bash
# Zet de cargo-target-dir van de huidige worktree op gedeeld of eigen.
#
# `just dev-setup` schrijft één gedeelde target-dir in de .cargo/config.toml van
# de hoofdcheckout; elke worktree eronder erft die via cargo's opwaartse zoektocht.
# Dat is gemeten de goedkoopste opstelling zolang er één build tegelijk draait, en
# de duurste zodra er twee draaien. Cargo neemt namelijk een exclusieve lock op de
# target-dir voor de duur van een hele build.
#
# Gemeten op deze machine (16 cores, NVMe, mold, warme caches):
#
#   gedeelde target-dir
#     `just build-check` in een verse worktree            1 s   (volledig hergebruik)
#     `just validate` alleen                              2 s
#     `just validate` tijdens een `just lint` van 45 s   38 s   (wachten op de lock)
#
#   eigen target-dir per worktree
#     `just validate` koud                               40 s
#     `just build-check` koud                           170 s   (~1,4 GB op schijf)
#     `just build-check` koud met warme sccache         121 s   (0 Rust-cachetreffers)
#
# Die laatste regel is de reden dat "eigen target-dir met een gedeelde sccache
# ervoor" hier geen alternatief is: sccache neemt de werkdirectory mee in zijn
# hash, dus twee worktrees op verschillende paden delen geen enkele Rust-compilatie.
# Gemeten: 480 misses, 0 hits.
#
# Vandaar deze schakelaar in plaats van een keuze voor iedereen. Gedeeld blijft de
# standaard; een agent die een lange build gaat draaien zet zijn worktree op eigen
# en blokkeert de anderen niet.
set -euo pipefail

MODE="${1:-}"
MARKER="# Generated by 'just target-isolated'. Gitignored — machine-local."

usage() {
    echo "gebruik: script/target-dir.sh <shared|isolated>" >&2
    exit 2
}

[ -n "$MODE" ] || usage

ROOT="${TARGET_DIR_ROOT:-$(git rev-parse --show-toplevel)}"
COMMON="${TARGET_DIR_COMMON:-$(dirname "$(git rev-parse --path-format=absolute --git-common-dir)")}"
CONFIG="$ROOT/.cargo/config.toml"

if [ "$ROOT" = "$COMMON" ]; then
    echo "Dit is de hoofdcheckout, niet een worktree." >&2
    echo "De gedeelde target-dir staat hier zelf; 'just dev-setup' beheert 'm." >&2
    exit 1
fi

case "$MODE" in
    isolated)
        if [ -f "$CONFIG" ] && ! grep -qF "$MARKER" "$CONFIG"; then
            echo "$CONFIG is niet door deze schakelaar gemaakt; ik overschrijf 'm niet." >&2
            exit 1
        fi
        mkdir -p "$ROOT/.cargo"
        {
            echo "$MARKER"
            echo "[build]"
            echo "target-dir = \"$ROOT/packages/target\""
        } > "$CONFIG"
        echo "Eigen target-dir: $ROOT/packages/target"
        echo "De eerste build is koud (~40 s voor 'just validate', ~170 s voor 'just build-check')."
        ;;
    shared)
        if [ -f "$CONFIG" ] && ! grep -qF "$MARKER" "$CONFIG"; then
            echo "$CONFIG is niet door deze schakelaar gemaakt; ik laat 'm staan." >&2
            exit 1
        fi
        rm -f "$CONFIG"
        rmdir "$ROOT/.cargo" 2>/dev/null || true
        echo "Terug op de gedeelde target-dir van de hoofdcheckout."
        ;;
    *)
        usage
        ;;
esac
