//! Tier-2 rendering: turns the code-derived model into the docs-site pages.
//!
//! The C4 diagrams and the per-crate pages the architecture site shows are
//! *derived* from `model.json`, never hand-drawn, so they cannot drift from the
//! code. We emit plain Markdown with fenced ```mermaid C4 blocks; the docs
//! build renders those through the existing `rehype-mermaid` +
//! `rehype-mermaid-alt.ts` pipeline (inline SVG with an accessible name from the
//! preceding heading). Output is deterministic — everything is sorted by
//! id/name and there is no timestamp — so `just arch-check` (regenerate + `git
//! diff --exit-code`) gates staleness the same way it does for `model.json`.

use std::collections::{BTreeMap, BTreeSet};

use crate::model::{Kind, Model, Node};

/// Repo-relative directory the generated pages live in (a section of the docs
/// content collection, so each file becomes a `/architecture/...` route).
pub const PAGES_DIR: &str = "docs/src/content/docs/architecture";

/// A single generated file: its repo-relative path and full contents.
pub struct Page {
    pub rel_path: String,
    pub content: String,
}

/// Banner stamped at the top of every generated page body, so an editor who
/// opens the file in the repo knows not to hand-edit it.
const BANNER: &str =
    "<!-- Generated by packages/arch-extract (`just arch-generate`). Do not edit by hand. -->";

/// Renders the full set of architecture pages from the model.
pub fn render(model: &Model) -> Vec<Page> {
    let crates = crate_nodes(model);

    let mut pages = vec![
        index_page(&crates),
        context_page(model, &crates),
        container_page(model, &crates),
        component_page(model, &crates),
    ];
    for c in &crates {
        pages.push(crate_page(model, c));
    }
    pages
}

// --- page builders -------------------------------------------------------

fn index_page(crates: &[&Node]) -> Page {
    let mut b = Body::new(
        "Architecture",
        "Code-derived C4 views and a page per crate, generated from the source tree.",
    );
    b.para(
        "These pages are generated from the workspace source by the \
         `arch-extract` build tool: the crate graph comes from `cargo metadata` \
         and the internal structure from a `syn` parse. Nothing here is drawn by \
         hand, so the diagrams cannot drift from the code — regenerate with `just \
         arch-generate`.",
    );

    b.heading("C4 views");
    b.line("- [System context](/architecture/context) — the platform as one system.");
    b.line("- [Containers](/architecture/container) — the ten crates and how they depend on each other.");
    b.line("- [Components](/architecture/component) — the top-level modules inside each crate.");
    b.blank();

    b.heading("Crates");
    for c in crates {
        let link = format!("/architecture/crates/{}", c.name);
        match doc_of(c) {
            Some(d) => b.line(&format!("- [{}]({}) — {}", c.name, link, d)),
            None => b.line(&format!("- [{}]({})", c.name, link)),
        }
    }

    Page {
        rel_path: format!("{PAGES_DIR}/index.md"),
        content: b.finish(),
    }
}

fn context_page(model: &Model, crates: &[&Node]) -> Page {
    let layers = layer_count(model, crates);
    let mut b = Body::new(
        "Architecture — System Context",
        "The RegelRecht platform as a single system (C4 level 1).",
    );
    b.para(
        "At the highest level RegelRecht is one system: a set of Rust crates that \
         together turn machine-readable Dutch law into an executable, auditable \
         platform. External actors (citizens, agencies, the BWB source) sit \
         outside the code-derived model and so are not shown here.",
    );
    b.heading("System context");
    let descr = format!(
        "Machine-readable Dutch law platform — {} Rust crates across {} dependency layers",
        crates.len(),
        layers
    );
    let mut m = Mermaid::new("C4Context", "RegelRecht — System Context");
    m.line(&format!(
        "System(regelrecht, \"RegelRecht\", \"{}\")",
        label(&descr)
    ));
    b.mermaid(m);
    Page {
        rel_path: format!("{PAGES_DIR}/context.md"),
        content: b.finish(),
    }
}

fn container_page(model: &Model, crates: &[&Node]) -> Page {
    let mut b = Body::new(
        "Architecture — Containers",
        "The ten workspace crates and their internal dependencies (C4 level 2).",
    );
    b.para(
        "Zooming into the system, each crate is a container. Arrows are normal \
         (non-dev, non-build) path dependencies between workspace members, which \
         yields the production layer graph `shared` → `law-model`/`auth` → \
         `engine`/`harvester`/`corpus` → `pipeline` → `admin`/`editor-api`/`tui`.",
    );
    b.heading("Containers");
    let mut m = Mermaid::new("C4Container", "RegelRecht — Containers");
    m.line("System_Boundary(regelrecht, \"RegelRecht\") {");
    for c in crates {
        let a = alias(&c.name);
        match doc_of(c) {
            Some(d) => m.line(&format!(
                "    Container({a}, \"{}\", \"Rust crate\", \"{}\")",
                label(&c.name),
                label(&d)
            )),
            None => m.line(&format!(
                "    Container({a}, \"{}\", \"Rust crate\")",
                label(&c.name)
            )),
        }
    }
    m.line("}");
    for (from, to) in depends_on_pairs(model) {
        m.line(&format!(
            "Rel({}, {}, \"depends on\")",
            alias(&from),
            alias(&to)
        ));
    }
    b.mermaid(m);
    Page {
        rel_path: format!("{PAGES_DIR}/container.md"),
        content: b.finish(),
    }
}

fn component_page(model: &Model, crates: &[&Node]) -> Page {
    let mut b = Body::new(
        "Architecture — Components",
        "The top-level modules inside each crate (C4 level 3).",
    );
    b.para(
        "Zooming into the containers, each crate's top-level modules are its \
         components. This is the system-wide overview; the per-crate pages drill \
         into a single crate's full module tree and types.",
    );
    b.heading("Components");
    let mut m = Mermaid::new("C4Component", "RegelRecht — Components (top-level modules)");
    for c in crates {
        let mods = top_level_modules(model, &c.name);
        if mods.is_empty() {
            continue;
        }
        m.line(&format!(
            "Container_Boundary({}, \"{}\") {{",
            alias(&c.name),
            label(&c.name)
        ));
        for md in mods {
            m.line(&component_line("    ", &c.name, md));
        }
        m.line("}");
    }
    b.mermaid(m);
    Page {
        rel_path: format!("{PAGES_DIR}/component.md"),
        content: b.finish(),
    }
}

fn crate_page(model: &Model, c: &Node) -> Page {
    let title = format!("Architecture — {} crate", c.name);
    let descr = doc_of(c).unwrap_or_else(|| format!("The {} crate.", c.name));
    let mut b = Body::new(&title, &descr);

    if let Some(d) = doc_of(c) {
        b.para(&d);
    }
    b.para(&format!("Source: `{}`", c.path));

    // Dependencies / dependents, both directions of the depends-on graph.
    let deps = deps_of(model, &c.name);
    let dependents = dependents_of(model, &c.name);
    b.heading("Dependencies");
    if deps.is_empty() {
        b.line("This crate depends on no other workspace crate.");
    } else {
        for d in &deps {
            b.line(&format!("- [{d}](/architecture/crates/{d})"));
        }
    }
    b.blank();
    b.heading("Dependents");
    if dependents.is_empty() {
        b.line("No other workspace crate depends on this crate.");
    } else {
        for d in &dependents {
            b.line(&format!("- [{d}](/architecture/crates/{d})"));
        }
    }
    b.blank();

    // Component diagram: this crate's modules.
    let mods = crate_modules(model, &c.name);
    b.heading("Components");
    if mods.is_empty() {
        b.line("This crate exposes no submodules.");
        b.blank();
    } else {
        let mut m = Mermaid::new("C4Component", &format!("{} — Components", c.name));
        m.line(&format!(
            "Container_Boundary({}, \"{}\") {{",
            alias(&c.name),
            label(&c.name)
        ));
        for md in &mods {
            m.line(&component_line("    ", &c.name, md));
        }
        m.line("}");
        b.mermaid(m);
    }

    // Type inventory.
    let types = crate_types(model, &c.name);
    b.heading("Types");
    if types.is_empty() {
        b.line("No public struct, enum or trait was extracted for this crate.");
    } else {
        b.line("| Type | Kind | Description |");
        b.line("| --- | --- | --- |");
        for t in &types {
            let kind = kind_word(t.kind);
            let d = doc_of(t).unwrap_or_default();
            b.line(&format!(
                "| `{}` | {} | {} |",
                cell(&t.name),
                kind,
                cell(&d)
            ));
        }
    }

    Page {
        rel_path: format!("{PAGES_DIR}/crates/{}.md", c.name),
        content: b.finish(),
    }
}

/// One `Component(...)` line for a module, aliased per crate so names are unique
/// across boundaries in a system-wide diagram.
fn component_line(indent: &str, crate_name: &str, m: &Node) -> String {
    let short = module_leaf(&m.id);
    let a = format!("{}__{}", alias(crate_name), alias(&module_path(&m.id)));
    match doc_of(m) {
        Some(d) => format!(
            "{indent}Component({a}, \"{}\", \"module\", \"{}\")",
            label(&short),
            label(&d)
        ),
        None => format!("{indent}Component({a}, \"{}\", \"module\")", label(&short)),
    }
}

// --- model queries -------------------------------------------------------

fn crate_nodes(model: &Model) -> Vec<&Node> {
    let mut v: Vec<&Node> = model
        .nodes
        .iter()
        .filter(|n| n.kind == Kind::Crate)
        .collect();
    v.sort_by(|a, b| a.name.cmp(&b.name));
    v
}

/// `crate:engine` / `mod:engine::service` / `type:engine::foo::Bar` -> `engine`.
fn crate_of(id: &str) -> Option<&str> {
    let after = id.split_once(':')?.1;
    Some(after.split("::").next().unwrap_or(after))
}

/// Module path without the crate prefix: `mod:engine::a::b` -> `a::b`.
fn module_path(id: &str) -> String {
    id.strip_prefix("mod:")
        .and_then(|s| s.split_once("::"))
        .map(|(_, rest)| rest.to_string())
        .unwrap_or_default()
}

/// Leaf module name: `mod:engine::a::b` -> `b`.
fn module_leaf(id: &str) -> String {
    id.rsplit("::").next().unwrap_or(id).to_string()
}

fn crate_modules<'a>(model: &'a Model, crate_name: &str) -> Vec<&'a Node> {
    let mut v: Vec<&Node> = model
        .nodes
        .iter()
        .filter(|n| n.kind == Kind::Module && crate_of(&n.id) == Some(crate_name))
        .collect();
    v.sort_by(|a, b| a.id.cmp(&b.id));
    v
}

/// Modules whose parent is the crate itself (depth-1), for the compact
/// system-wide component view.
fn top_level_modules<'a>(model: &'a Model, crate_name: &str) -> Vec<&'a Node> {
    let crate_id = format!("crate:{crate_name}");
    let mut v: Vec<&Node> = model
        .nodes
        .iter()
        .filter(|n| n.kind == Kind::Module && n.parent.as_deref() == Some(crate_id.as_str()))
        .collect();
    v.sort_by(|a, b| a.id.cmp(&b.id));
    v
}

fn crate_types<'a>(model: &'a Model, crate_name: &str) -> Vec<&'a Node> {
    let mut v: Vec<&Node> = model
        .nodes
        .iter()
        .filter(|n| {
            matches!(n.kind, Kind::Struct | Kind::Enum | Kind::Trait)
                && crate_of(&n.id) == Some(crate_name)
        })
        .collect();
    v.sort_by(|a, b| a.id.cmp(&b.id));
    v
}

/// All `depends-on` (from-short, to-short) pairs, sorted and deduped.
fn depends_on_pairs(model: &Model) -> Vec<(String, String)> {
    let mut set: BTreeSet<(String, String)> = BTreeSet::new();
    for e in &model.edges {
        if e.kind != crate::model::EdgeKind::DependsOn {
            continue;
        }
        if let (Some(f), Some(t)) = (e.from.strip_prefix("crate:"), e.to.strip_prefix("crate:")) {
            set.insert((f.to_string(), t.to_string()));
        }
    }
    set.into_iter().collect()
}

fn deps_of(model: &Model, crate_name: &str) -> Vec<String> {
    depends_on_pairs(model)
        .into_iter()
        .filter(|(f, _)| f == crate_name)
        .map(|(_, t)| t)
        .collect()
}

fn dependents_of(model: &Model, crate_name: &str) -> Vec<String> {
    depends_on_pairs(model)
        .into_iter()
        .filter(|(_, t)| t == crate_name)
        .map(|(f, _)| f)
        .collect()
}

/// Number of dependency layers over the crate `depends-on` DAG: the longest
/// chain of crates each depending on the next. Purely a summary figure for the
/// context page, computed deterministically from the edges.
fn layer_count(model: &Model, crates: &[&Node]) -> usize {
    let mut deps: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for c in crates {
        deps.entry(c.name.clone()).or_default();
    }
    for (f, t) in depends_on_pairs(model) {
        deps.entry(f).or_default().push(t);
    }
    let mut memo: BTreeMap<String, usize> = BTreeMap::new();
    fn depth(
        name: &str,
        deps: &BTreeMap<String, Vec<String>>,
        memo: &mut BTreeMap<String, usize>,
    ) -> usize {
        if let Some(&d) = memo.get(name) {
            return d;
        }
        // Guard against cycles (none expected in the workspace) by memoizing 1
        // up front; a re-entrant visit then reads that instead of recursing.
        memo.insert(name.to_string(), 1);
        let mut best = 1;
        if let Some(children) = deps.get(name) {
            for c in children {
                best = best.max(1 + depth(c, deps, memo));
            }
        }
        memo.insert(name.to_string(), best);
        best
    }
    crates
        .iter()
        .map(|c| depth(&c.name, &deps, &mut memo))
        .max()
        .unwrap_or(0)
}

// --- small formatting helpers -------------------------------------------

fn doc_of(n: &Node) -> Option<String> {
    n.doc
        .as_ref()
        .map(|d| d.trim().to_string())
        .filter(|d| !d.is_empty())
}

fn kind_word(k: Kind) -> &'static str {
    match k {
        Kind::Struct => "struct",
        Kind::Enum => "enum",
        Kind::Trait => "trait",
        Kind::Crate => "crate",
        Kind::Binary => "binary",
        Kind::Module => "module",
        Kind::Method => "method",
        Kind::Fn => "fn",
    }
}

/// Mermaid C4 aliases must be identifier-safe: fold anything but ASCII
/// alphanumerics to `_` (so `editor-api` -> `editor_api`, `a::b` -> `a__b`).
fn alias(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// Sanitizes a string for use inside a double-quoted Mermaid label: quotes
/// become apostrophes and any newline collapses to a space.
fn label(s: &str) -> String {
    s.replace('"', "'")
        .replace(['\n', '\r'], " ")
        .trim()
        .to_string()
}

/// Sanitizes a string for a Markdown table cell: escape pipes and collapse
/// newlines so a doc-comment cannot break the table.
fn cell(s: &str) -> String {
    s.replace('|', "\\|")
        .replace(['\n', '\r'], " ")
        .trim()
        .to_string()
}

// --- markdown/mermaid builders ------------------------------------------

/// Accumulates a page body with a leading frontmatter block and the shared
/// generated-file banner, guaranteeing no trailing whitespace and exactly one
/// terminating newline (so the pre-commit whitespace/eof hooks stay happy and
/// the output is byte-stable for `arch-check`).
struct Body {
    out: String,
}

impl Body {
    fn new(title: &str, description: &str) -> Self {
        let mut out = String::new();
        out.push_str("---\n");
        out.push_str(&format!("title: \"{}\"\n", label(title)));
        out.push_str(&format!("description: \"{}\"\n", label(description)));
        out.push_str("---\n\n");
        out.push_str(BANNER);
        out.push_str("\n\n");
        Self { out }
    }

    fn para(&mut self, text: &str) {
        self.out.push_str(text);
        self.out.push_str("\n\n");
    }

    fn heading(&mut self, text: &str) {
        self.out.push_str("## ");
        self.out.push_str(text);
        self.out.push_str("\n\n");
    }

    fn line(&mut self, text: &str) {
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }

    fn mermaid(&mut self, m: Mermaid) {
        self.out.push_str("```mermaid\n");
        self.out.push_str(&m.body);
        self.out.push_str("```\n\n");
    }

    /// Collapses any accidental trailing blank lines to a single newline.
    fn finish(mut self) -> String {
        while self.out.ends_with("\n\n") {
            self.out.pop();
        }
        if !self.out.ends_with('\n') {
            self.out.push('\n');
        }
        self.out
    }
}

/// A fenced Mermaid C4 diagram body (without the code fence), one 4-space
/// indented statement per line under a `title`.
struct Mermaid {
    body: String,
}

impl Mermaid {
    fn new(diagram: &str, title: &str) -> Self {
        let mut body = String::new();
        body.push_str(diagram);
        body.push('\n');
        body.push_str(&format!("    title {}\n", label(title)));
        Self { body }
    }

    fn line(&mut self, text: &str) {
        self.body.push_str("    ");
        self.body.push_str(text);
        self.body.push('\n');
    }
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]
mod tests {
    use super::*;
    use crate::model::{Edge, EdgeKind, Level};

    fn crate_node(short: &str, doc: Option<&str>) -> Node {
        Node {
            id: format!("crate:{short}"),
            level: Level::Container,
            kind: Kind::Crate,
            lang: "rust".to_string(),
            name: short.to_string(),
            path: format!("packages/{short}"),
            parent: None,
            doc: doc.map(str::to_string),
        }
    }

    fn module_node(crate_short: &str, path: &str, doc: Option<&str>) -> Node {
        let parent = if path.contains("::") {
            let head = path.rsplit_once("::").unwrap().0;
            format!("mod:{crate_short}::{head}")
        } else {
            format!("crate:{crate_short}")
        };
        Node {
            id: format!("mod:{crate_short}::{path}"),
            level: Level::Component,
            kind: Kind::Module,
            lang: "rust".to_string(),
            name: path.rsplit("::").next().unwrap().to_string(),
            path: format!("packages/{crate_short}/src/{path}.rs"),
            parent: Some(parent),
            doc: doc.map(str::to_string),
        }
    }

    fn sample() -> Model {
        Model::new(
            vec![
                crate_node("engine", Some("Law execution engine")),
                crate_node("shared", None),
                crate_node("editor-api", Some("Editor backend")),
                module_node("engine", "service", Some("Execution service")),
                module_node("engine", "service::inner", None),
                Node {
                    id: "type:engine::service::LawExecutionService".to_string(),
                    level: Level::Component,
                    kind: Kind::Struct,
                    lang: "rust".to_string(),
                    name: "LawExecutionService".to_string(),
                    path: "packages/engine/src/service.rs".to_string(),
                    parent: Some("mod:engine::service".to_string()),
                    doc: Some("Runs a law".to_string()),
                },
            ],
            vec![
                Edge {
                    from: "crate:engine".to_string(),
                    to: "crate:shared".to_string(),
                    kind: EdgeKind::DependsOn,
                },
                Edge {
                    from: "crate:editor-api".to_string(),
                    to: "crate:engine".to_string(),
                    kind: EdgeKind::DependsOn,
                },
            ],
        )
    }

    #[test]
    fn renders_expected_page_set() {
        let pages = render(&sample());
        let paths: Vec<&str> = pages.iter().map(|p| p.rel_path.as_str()).collect();
        assert!(paths.contains(&"docs/src/content/docs/architecture/index.md"));
        assert!(paths.contains(&"docs/src/content/docs/architecture/context.md"));
        assert!(paths.contains(&"docs/src/content/docs/architecture/container.md"));
        assert!(paths.contains(&"docs/src/content/docs/architecture/component.md"));
        // One page per crate.
        assert!(paths.contains(&"docs/src/content/docs/architecture/crates/engine.md"));
        assert!(paths.contains(&"docs/src/content/docs/architecture/crates/editor-api.md"));
        assert!(paths.contains(&"docs/src/content/docs/architecture/crates/shared.md"));
    }

    #[test]
    fn deterministic() {
        let a = render(&sample());
        let b = render(&sample());
        assert_eq!(a.len(), b.len());
        for (x, y) in a.iter().zip(b.iter()) {
            assert_eq!(x.rel_path, y.rel_path);
            assert_eq!(x.content, y.content);
        }
    }

    #[test]
    fn container_page_has_c4_and_rels() {
        let pages = render(&sample());
        let c = pages
            .iter()
            .find(|p| p.rel_path.ends_with("container.md"))
            .unwrap();
        assert!(c.content.contains("```mermaid"));
        assert!(c.content.contains("C4Container"));
        // Hyphenated crate name is aliased for the mermaid node id.
        assert!(c.content.contains("Container(editor_api,"));
        assert!(c
            .content
            .contains("Rel(editor_api, engine, \"depends on\")"));
    }

    #[test]
    fn crate_page_lists_deps_and_types() {
        let pages = render(&sample());
        let engine = pages
            .iter()
            .find(|p| p.rel_path.ends_with("crates/engine.md"))
            .unwrap();
        assert!(engine
            .content
            .contains("[shared](/architecture/crates/shared)"));
        assert!(engine
            .content
            .contains("[editor-api](/architecture/crates/editor-api)"));
        assert!(engine.content.contains("`LawExecutionService`"));
        assert!(engine.content.contains("C4Component"));
    }

    #[test]
    fn files_end_with_single_newline_and_no_trailing_ws() {
        for p in render(&sample()) {
            assert!(p.content.ends_with('\n'), "{} lacks newline", p.rel_path);
            assert!(
                !p.content.ends_with("\n\n"),
                "{} has trailing blank line",
                p.rel_path
            );
            for line in p.content.lines() {
                assert_eq!(
                    line.trim_end(),
                    line,
                    "{} has trailing whitespace on a line",
                    p.rel_path
                );
            }
        }
    }
}
